name: validation_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the build number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS-style widgets
  cupertino_icons: ^1.0.8

  # SQLite for local data storage
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

  # State management
  provider: ^6.1.5

  # Persist simple user settings
  shared_preferences: ^2.1.0
  
  # Date and number formatting
  intl: ^0.20.2
  
  # Charting library for visualization
  fl_chart: ^1.0.0
  
  # File sharing and picking
  share_plus: ^11.0.0
  file_picker: ^10.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints for good Flutter practices
  flutter_lints: ^5.0.0

flutter:
  # Include the Material Icons font so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # family name and a list of assets.